name: Check frontend code build
on: 
  pull_request:
    paths:
      - 'web-app/client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Set Node.js
          uses: actions/setup-node@v4
          with:
            node-version-file: 'web-app/client/.nvmrc'

        - name: Load .env.example file
          uses: falti/dotenv-action@v1.1.2
          with:
            path: web-app/client/.env.example
            export-variables: true
            keys-case: bypass

        - name: Install server dependencies
          working-directory: web-app/server
          run: yarn install --immutable

        - name: Generate server schema
          working-directory: web-app/server
          run: yarn generate
        
        - name: Install client dependencies
          working-directory: web-app/client
          run: yarn install --immutable

        - name: Generate client types
          working-directory: web-app/client
          run: |
            yarn codegen:server
            yarn codegen:cms
        
        - name: Check typing
          working-directory: web-app/client
          run: yarn tsc --noEmit
        
        - name: Build client
          if: always()
          working-directory: web-app/client
          run: yarn build

